---



- name: Play no.01 Config OSPF on r1, r2 & advertise their networks
  hosts: r1
  connection: local
  gather_facts: no

  vars:
    cli:
      username: tison
      password: cisco12345

  tasks:
     - name: Task no.03 Config Loopback Interface on r1 & r2
       with_items: "{{ ospfBasicConfig }}"
       ios_config:
       
          provider: "{{ cli }}"
          authorize: yes
          parents: int "{{ item.inter }}" 
          lines:
             #- int 
             - ip add "{{ item.ip_addr }}"
             - desc "{{ item.desc }}"




     - name: Task no.04 Config OSPF on r1 & r2 with process ID 11
       #with_items: "{{ ospfConfigInfo }}"
       ios_config:
          provider: "{{ cli }}"
          lines:
             - networks "{{ advNet00 }}" 0.0.0.0 area 0
             - networks "{{ advNet01 }}" 0.0.0.0 area 0
             - networks "{{ advNet02 }}" 0.0.0.0 area 0
          parent:
             - router ospf 11
